"""Build g03_all9_replay.script - all 9 spacecraft in one GMAT run, no solvers.

Reads the converged burn-1 components from the g02_sc*_summary.txt reports and
the slot insertion states from g01_slot*.txt (both in output/gmat/),
then writes a replay script: all 9 spacecraft leave on the same launch day, but
each from its OWN release group's post-Ariane state (Ariane 6 supports
multiple targeted separations), fires its converged burn-1 immediately, coasts
to its insertion epoch, fires the velocity-match insertion burn, and the whole
fleet then flies its 2-year operational life (launch -> end of mission).

Propagation runs in 1-day steps and writes g03_all9_daily.txt: A1MJD then, per
spacecraft, SunEarthRot X, Y (km) and Sun RMAG (km) - the data file behind
the exported results package.

Open the script in the GMAT GUI and press Run to watch (RotView = wide
rotating frame, EarthZoom = separation close-up).
"""
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
DRO_DIR = HERE.parent
ROOT = DRO_DIR.parent
sys.path.insert(0, str(DRO_DIR))
sys.path.insert(0, str(ROOT / "scripts"))

from paths import GMAT_OUTPUT, GENERATED_GMAT, PYTHON_OUTPUT, ensure_runtime_dirs
from lambert import lambert, MU, AU, DAY   # noqa: F401  (path setup for consistency)
from campaign_config import A1_LAUNCH

ensure_runtime_dirs()
GMAT_OUT = GMAT_OUTPUT
NSAT = 9
YEAR_D = 365.25636
R_SEP = 1.5e6
N_E = 2 * np.pi / (YEAR_D * DAY)

# departure design + insertion days from departure.py
with (PYTHON_OUTPUT / "campaign_departure.json").open("r", encoding="utf-8") as _f:
    DEP = json.load(_f)
INS_DAY = [int(m["day"]) for m in DEP["members"]]
EOM_DAY = max(INS_DAY) + 730          # 2-year operational life after full deployment


def departure_state(vinf_vec):
    """Departure state in the SunEarthRot frame for a given asymptote:
    1.5 Mkm from Earth along the asymptote, rotating-frame velocity =
    vinf - omega x r."""
    u = vinf_vec / np.linalg.norm(vinf_vec)
    r_rot = R_SEP * u
    v_rot = vinf_vec - N_E * np.array([-r_rot[1], r_rot[0], 0.0])
    return r_rot, v_rot


# each spacecraft may belong to its own release group with its own asymptote
# (Ariane 6 supports multiple targeted separations); fall back to a single
# global vinf_vec for older single-asymptote campaign_departure.json files.
dep_state = {}
for k in range(NSAT):
    m = DEP["members"][k]
    vinf_vec = np.array(m["vinf_vec"]) if "vinf_vec" in m else np.array(DEP["vinf_vec"])
    dep_state[k] = departure_state(vinf_vec)

b1, tgtv = {}, {}
for k in range(NSAT):
    row = (GMAT_OUT / f"g02_sc{k}_summary.txt").read_text().split()
    b1[k] = (float(row[2]), float(row[3]), float(row[4]))
    row = (GMAT_OUT / f"g01_slot{k}.txt").read_text().split()
    tgtv[k] = (float(row[5]), float(row[6]), float(row[7]))

s = """% g03_all9_replay.script - auto-generated by gen_all9_replay.py
% All 9 spacecraft, one launch, converged burns (no solvers). Open in the GMAT
% GUI and press Run. Daily fleet states go to output/g03_all9_daily.txt.

Create CoordinateSystem SunEcl;
GMAT SunEcl.Origin = Sun;
GMAT SunEcl.Axes   = MJ2000Ec;

Create CoordinateSystem SunEarthRot;
GMAT SunEarthRot.Origin    = Earth;
GMAT SunEarthRot.Axes      = ObjectReferenced;
GMAT SunEarthRot.XAxis     = R;
GMAT SunEarthRot.ZAxis     = N;
GMAT SunEarthRot.Primary   = Sun;
GMAT SunEarthRot.Secondary = Earth;

Create ForceModel HelioFM;
GMAT HelioFM.CentralBody  = Sun;
GMAT HelioFM.PointMasses  = {Sun, Earth, Luna, Venus, Mars, Jupiter};
GMAT HelioFM.Drag         = None;
GMAT HelioFM.SRP          = On;
GMAT HelioFM.SRP.Flux     = 1367;
GMAT HelioFM.SRP.SRPModel = Spherical;
GMAT HelioFM.ErrorControl = RSSStep;

Create Propagator Helio;
GMAT Helio.FM              = HelioFM;
GMAT Helio.Type            = PrinceDormand78;
GMAT Helio.InitialStepSize = 3600;
GMAT Helio.Accuracy        = 1e-11;
GMAT Helio.MinStep         = 0;
GMAT Helio.MaxStep         = 86400;
GMAT Helio.MaxStepAttempts = 50;
"""

for k in range(NSAT):
    r_rot, v_rot = dep_state[k]
    s += f"""
Create Spacecraft S{k+1};
GMAT S{k+1}.DateFormat       = A1ModJulian;
GMAT S{k+1}.Epoch            = '{A1_LAUNCH:.9f}';
GMAT S{k+1}.CoordinateSystem = SunEarthRot;
GMAT S{k+1}.DisplayStateType = Cartesian;
GMAT S{k+1}.X  = {r_rot[0]:.6f};
GMAT S{k+1}.Y  = {r_rot[1]:.6f};
GMAT S{k+1}.Z  = 0.0;
GMAT S{k+1}.VX = {v_rot[0]:.9f};
GMAT S{k+1}.VY = {v_rot[1]:.9f};
GMAT S{k+1}.VZ = 0.0;
GMAT S{k+1}.DryMass = 265;
GMAT S{k+1}.Cr      = 1.3;
GMAT S{k+1}.SRPArea = 4.0;

Create ImpulsiveBurn B1_{k+1};
GMAT B1_{k+1}.CoordinateSystem = SunEarthRot;
GMAT B1_{k+1}.Element1 = {b1[k][0]:.9f};
GMAT B1_{k+1}.Element2 = {b1[k][1]:.9f};
GMAT B1_{k+1}.Element3 = {b1[k][2]:.9f};

Create ImpulsiveBurn B2_{k+1};
GMAT B2_{k+1}.CoordinateSystem = SunEarthRot;
"""

all_sats = ", ".join(f"S{k+1}" for k in range(NSAT))
rpt_cols = " ".join(f"S{k+1}.SunEarthRot.X S{k+1}.SunEarthRot.Y S{k+1}.Sun.RMAG"
                    for k in range(NSAT))

REPLAY_REPORT = (GMAT_OUT / "g03_all9_daily.txt").resolve()
REPLAY_REPORT.unlink(missing_ok=True)

s += f"""
Create ReportFile rptAll;
GMAT rptAll.Filename         = '{REPLAY_REPORT.as_posix()}';
GMAT rptAll.WriteHeaders     = false;
GMAT rptAll.SolverIterations = None;
GMAT rptAll.Precision        = 12;

Create OrbitView RotView;
GMAT RotView.Add               = {{{all_sats}, Earth}};
GMAT RotView.CoordinateSystem  = SunEarthRot;
GMAT RotView.ViewPointReference = Earth;
GMAT RotView.ViewPointVector   = [0 0 150000000];
GMAT RotView.ViewDirection     = Earth;
GMAT RotView.ViewUpAxis        = Y;
GMAT RotView.ShowPlot          = true;
GMAT RotView.SolverIterations  = None;

Create OrbitView EarthZoom;
GMAT EarthZoom.Add               = {{{all_sats}, Earth}};
GMAT EarthZoom.CoordinateSystem  = SunEarthRot;
GMAT EarthZoom.ViewPointReference = Earth;
GMAT EarthZoom.ViewPointVector   = [0 0 12000000];
GMAT EarthZoom.ViewDirection     = Earth;
GMAT EarthZoom.ViewUpAxis        = Y;
GMAT EarthZoom.ShowPlot          = true;
GMAT EarthZoom.SolverIterations  = None;

Create Variable q;

BeginMissionSequence;

% burn 1 for everyone, right after separation
"""
for k in range(NSAT):
    s += f"Maneuver B1_{k+1}(S{k+1});\n"
s += f"Report rptAll S1.A1ModJulian {rpt_cols};\n"

# daily propagation, pausing at each insertion epoch to fire that burn
events = sorted(set(INS_DAY))
prev = 0
for day in events:
    s += f"""
For q = 1:1:{day - prev};
   Propagate Helio({all_sats}) {{S1.ElapsedDays = 1}};
   Report rptAll S1.A1ModJulian {rpt_cols};
EndFor;
"""
    for k in range(NSAT):
        if INS_DAY[k] == day:
            s += f"B2_{k+1}.Element1 = {tgtv[k][0]:.9f} - S{k+1}.SunEarthRot.VX;\n"
            s += f"B2_{k+1}.Element2 = {tgtv[k][1]:.9f} - S{k+1}.SunEarthRot.VY;\n"
            s += f"B2_{k+1}.Element3 = {tgtv[k][2]:.9f} - S{k+1}.SunEarthRot.VZ;\n"
            s += f"Maneuver B2_{k+1}(S{k+1});\n"
    prev = day

s += f"""
% operational phase to end of mission (2 years after the last insertion)
For q = 1:1:{EOM_DAY - prev};
   Propagate Helio({all_sats}) {{S1.ElapsedDays = 1}};
   Report rptAll S1.A1ModJulian {rpt_cols};
EndFor;
"""

path = GENERATED_GMAT / "g03_all9_replay.script"
path.write_text(s, encoding="utf-8")
print("wrote", path, f"(daily states to {REPLAY_REPORT}, launch -> day {EOM_DAY})")
